vcs:
  type: git
agents:
  available:
  - claude
  auto_commit: true
project:
  uuid: c98b935f-233d-4ac3-9d6d-238a7ab2de66
  slug: muster
  node_id: 415a1490fb46
  build_id: d0c9dda3-5d3d-48e5-9289-e6c4294e0511
